# PUT /api/v1/auth/password
# Authorization: Bearer {{token}}

PUT http://127.0.0.1:3000/api/v1/auth/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "123456",
  "newPassword": "654321"
}
