[package]
name = "i-thinking"
version = "0.1.0"
description = "i thinking is a privacy-first extension that enhances your browsing experience with intelligent features while prioritizing your data security."
authors = ["layen"]
edition = "2024"

# [profile.release]
# opt-level = 2       # 降低优化级别 (从 3 改为 2)
# lto = true          # 链接时优化（平衡大小与速度）
# codegen-units = 1   # 单线程代码生成（提升优化）
# incremental = false # 禁用增量编译（避免优化冲突）
# panic = "abort"     # 替换展开为直接终止（减小体积）
# strip = "symbols"   # 移除调试符号（Rust 1.59+）

# bin
[[bin]]
name = "i-thinking"
path = "src/bin/thinking.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "thinking"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
tauri = { version = "2.9.5", features = ["protocol-asset", "macos-private-api", "devtools", "tray-icon"] }
tauri-plugin-opener = "2.5.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sysinfo = "0.37.2"
tauri-plugin-fs = "2"
tauri-plugin-websocket = "2"
tauri-plugin-dialog = "2"
tauri-plugin-localhost = "2"
tauri-plugin-shell = "2"
tauri-plugin-store = "2"
tauri-plugin-process = "2"
tauri-plugin-notification = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-log = "2"
tauri-plugin-sql = { version = "2", features = ["postgres"] }
tauri-plugin-http = { version = "2", features = ["unsafe-headers"] }
tauri-plugin-devtools = "2.0.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-cli = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-positioner = { version = "2.0.0", features = ["tray-icon"] }
