[package]
name    = "service"
version = "0.1.0"
edition = "2024"

# [profile.release]
# opt-level = 2       # 降低优化级别 (从 3 改为 2)
# lto = true          # 链接时优化（平衡大小与速度）
# codegen-units = 1   # 单线程代码生成（提升优化）
# incremental = false # 禁用增量编译（避免优化冲突）
# panic = "abort"     # 替换展开为直接终止（减小体积）
# strip = "symbols"   # 移除调试符号（Rust 1.59+）

[lib]
name       = "core"
path       = "src/lib.rs"
crate-type = ["rlib", "cdylib", "staticlib"]

[[bin]]
name = "service"
path = "src/bin/service.rs"

[[bin]]
name = "generate"
path = "src/bin/generate.rs"

[dependencies]
actix-cors      = "0.7.1"
actix-files     = "0.6.9"
actix-multipart = "0.7.2"
actix-web       = { version = "4.12.1", features = ["rustls"] }
anyhow          = "1.0.100"
argon2          = "0.5.3"
aes-gcm         = "0.10"
chrono          = { version = "0.4.42", features = ["serde"] }
dotenv          = "0.15.0"
env_logger      = "0.11.8"
futures         = "0.3.31"
jsonwebtoken    = { version = "10.2.0", features = ["rust_crypto"] }
mongodb         = "3.4.1"
reqwest         = { version = "0.13.1", features = ["json", "query", "rustls"] }
serde           = { version = "1.0.228", features = ["derive"] }
serde_json      = "1.0.148"
sha2            = "0.10.9"
thiserror       = "2.0.17"
tokio           = { version = "1.49.0", features = ["full"] }
uuid            = { version = "1.19.0", features = ["v4"] }
base64          = "0.22.1"
rand            = "0.9.2"
colored         = "3.0.0"
comfy-table     = { version = "7.2.1", features = ["custom_styling"] }
dialoguer       = "0.12.0"
