[package]
name    = "service"
version = "0.1.0"
edition = "2024"

# [profile.release]
# opt-level = 2       # 降低优化级别 (从 3 改为 2)
# lto = true          # 链接时优化（平衡大小与速度）
# codegen-units = 1   # 单线程代码生成（提升优化）
# incremental = false # 禁用增量编译（避免优化冲突）
# panic = "abort"     # 替换展开为直接终止（减小体积）
# strip = "symbols"   # 移除调试符号（Rust 1.59+）

[lib]
name       = "core"
path       = "src/lib.rs"
crate-type = ["rlib", "cdylib", "staticlib"]

[[bin]]
name = "service"
path = "src/bin/service.rs"

[[bin]]
name = "generate"
path = "src/bin/generate.rs"

[dependencies]
actix-cors      = "0.7.1"
actix-files     = "0.6.10"
actix-multipart = "0.7.2"
actix-web       = { version = "4.13.0", features = ["rustls"] }
anyhow          = "1.0.102"
argon2          = "0.5.3"
aes-gcm         = "0.10"
chrono          = { version = "0.4.44", features = ["serde"] }
dotenv          = "0.15.0"
env_logger      = "0.11.10"
futures         = "0.3.32"
jsonwebtoken    = { version = "10.4.0", features = ["rust_crypto"] }
mongodb         = "3.6.0"
reqwest         = { version = "0.13.3", features = ["json", "query", "rustls"] }
serde           = { version = "1.0.228", features = ["derive"] }
serde_json      = "1.0.149"
sha2            = "0.11.0"
thiserror       = "2.0.18"
tokio           = { version = "1.52.3", features = ["full"] }
uuid            = { version = "1.23.1", features = ["v4"] }
base64          = "0.22.1"
rand            = "0.10.1"
colored         = "3.1.1"
comfy-table     = { version = "7.2.2", features = ["custom_styling"] }
dialoguer       = "0.12.0"
