packages:
  - 'apps/*'
  - 'packages/*'

# 仅构建这些依赖
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - core-js
  - electron
  - esbuild
  - msw
  - unrs-resolver
