packages:
  - apps/*
  - packages/*

catalog:
  electron: ^40.1.0
  electron-builder: ^26.4.0

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - better-sqlite3
  - core-js
  - electron
  - electron-winstaller
  - esbuild
  - msw
  - prisma
  - unrs-resolver
