# 用户 — 获取列表 / 单个
# 先执行 signin，再执行下方请求

@host = http://127.0.0.1:3000
@username = admin
@password = 123456

# @name signin
POST {{host}}/api/v1/auth/signin
Content-Type: application/json
Accept: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###
@token = {{signin.response.body.data.token}}
@userId = {{signin.response.body.data.id}}

GET {{host}}/api/v1/users
Authorization: Bearer {{token}}
Accept: application/json

###
GET {{host}}/api/v1/users/{{userId}}
Authorization: Bearer {{token}}
Accept: application/json
