const DEFAULT_ABORT_TIMEOUT_MS = 1000
const DEFAULT_SKELETON_MIN_MS = 200
const DEFAULT_SKELETON_FADE_MS = 200

export {
  DEFAULT_ABORT_TIMEOUT_MS,
  DEFAULT_SKELETON_FADE_MS,
  DEFAULT_SKELETON_MIN_MS
}
