/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AInput: typeof import('ant-design-vue/es')['Input']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AppBookmark: typeof import('./../components/applications/app-bookmark/app-bookmark.vue')['default']
    'AppBookmarkDialog copy': typeof import('./../components/applications/app-bookmark/app-bookmark-dialog copy.vue')['default']
    AppBookmarkIcon: typeof import('./../components/applications/app-bookmark/app-bookmark-icon.vue')['default']
    AppBookmarkWindow: typeof import('./../components/applications/app-bookmark/app-bookmark-window.vue')['default']
    AppCalendar: typeof import('./../components/applications/app-calendar/app-calendar.vue')['default']
    AppCalendarIcon: typeof import('./../components/applications/app-calendar/app-calendar-icon.vue')['default']
    AppCalendarWindow: typeof import('./../components/applications/app-calendar/app-calendar-window.vue')['default']
    AppController: typeof import('./../components/app-controller/app-controller.vue')['default']
    AppExample: typeof import('./../components/applications/app-example/app-example.vue')['default']
    AppExampleIcon: typeof import('./../components/applications/app-example/app-example-icon.vue')['default']
    AppExampleWindow: typeof import('./../components/applications/app-example/app-example-window.vue')['default']
    AppMenu: typeof import('./../components/app-menu/app-menu.vue')['default']
    AppNotepad: typeof import('./../components/applications/app-notepad/app-notepad.vue')['default']
    AppNotepadIcon: typeof import('./../components/applications/app-notepad/app-notepad-icon.vue')['default']
    AppNotepadWindow: typeof import('./../components/applications/app-notepad/app-notepad-window.vue')['default']
    AppSettings: typeof import('./../components/app-settings/app-settings.vue')['default']
    AppStore: typeof import('./../components/applications/app-store/app-store.vue')['default']
    AppStoreIcon: typeof import('./../components/applications/app-store/app-store-icon.vue')['default']
    AppStoreWindow: typeof import('./../components/applications/app-store/app-store-window.vue')['default']
    AppWeb: typeof import('./../components/applications/app-web/app-web.vue')['default']
    AppWebIcon: typeof import('./../components/applications/app-web/app-web-icon.vue')['default']
    AppWebWindow: typeof import('./../components/applications/app-web/app-web-window.vue')['default']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASpaceCompact: typeof import('ant-design-vue/es')['Compact']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStyleProvider: typeof import('ant-design-vue/es')['StyleProvider']
    ComboboxTrigger: typeof import('./../components/combobox-trigger/combobox-trigger.vue')['default']
    copy: typeof import('./../components/applications/app-bookmark/app-bookmark-dialog copy.vue')['default']
    DropZone: typeof import('./../components/DropZone.vue')['default']
    'ILocal:appleFilled': typeof import('~icons/local/apple-filled')['default']
    'ILocal:batteryFullOutline': typeof import('~icons/local/battery-full-outline')['default']
    'ILocal:macToggle': typeof import('~icons/local/mac-toggle')['default']
    'ILocal:search': typeof import('~icons/local/search')['default']
    'ILocal:wifi': typeof import('~icons/local/wifi')['default']
    ReDock: typeof import('./../components/re-dock/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
