/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AppBookmark: typeof import('./../components/applications/app-bookmark/app-bookmark.vue')['default']
    AppBookmarkDialog: typeof import('./../components/applications/app-bookmark/app-bookmark-dialog.vue')['default']
    AppBookmarkIcon: typeof import('./../components/applications/app-bookmark/app-bookmark-icon.vue')['default']
    AppCalendar: typeof import('./../components/applications/app-calendar/app-calendar.vue')['default']
    AppCalendarDialog: typeof import('./../components/applications/app-calendar/app-calendar-dialog.vue')['default']
    AppCalendarIcon: typeof import('./../components/applications/app-calendar/app-calendar-icon.vue')['default']
    AppController: typeof import('./../components/app-controller/app-controller.vue')['default']
    AppExample: typeof import('./../components/applications/app-example/app-example.vue')['default']
    AppExampleDialog: typeof import('./../components/applications/app-example/app-example-dialog.vue')['default']
    AppExampleIcon: typeof import('./../components/applications/app-example/app-example-icon.vue')['default']
    AppMenu: typeof import('./../components/app-menu/app-menu.vue')['default']
    AppSettings: typeof import('./../components/app-settings/app-settings.vue')['default']
    AppStore: typeof import('./../components/applications/app-store/app-store.vue')['default']
    AppStoreDialog: typeof import('./../components/applications/app-store/app-store-dialog.vue')['default']
    AppStoreIcon: typeof import('./../components/applications/app-store/app-store-icon.vue')['default']
    AppWeb: typeof import('./../components/applications/app-web/app-web.vue')['default']
    AppWebDialog: typeof import('./../components/applications/app-web/app-web-dialog.vue')['default']
    AppWebIcon: typeof import('./../components/applications/app-web/app-web-icon.vue')['default']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASpaceCompact: typeof import('ant-design-vue/es')['Compact']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStyleProvider: typeof import('ant-design-vue/es')['StyleProvider']
    ComboboxTrigger: typeof import('./../components/combobox-trigger/combobox-trigger.vue')['default']
    IconLocalAppleFilled: typeof import('~icons/local/apple-filled')['default']
    IconLocalBatteryFullOutline: typeof import('~icons/local/battery-full-outline')['default']
    IconLocalMacToggle: typeof import('~icons/local/mac-toggle')['default']
    IconLocalSearch: typeof import('~icons/local/search')['default']
    IconLocalWifi: typeof import('~icons/local/wifi')['default']
    ReDock: typeof import('./../components/re-dock/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/svg-icon/SvgIcon.vue')['default']
  }
}
