/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AppBookmarkIcon: typeof import('./../components/bookmarks/app-bookmark-icon.vue')['default']
    AppController: typeof import('./../components/app-controller/app-controller.vue')['default']
    AppExample: typeof import('./../components/example/app-example.vue')['default']
    AppExampleIcon: typeof import('./../components/example/app-example-icon.vue')['default']
    AppExampleWindow: typeof import('./../components/example/app-example-window.vue')['default']
    AppStore: typeof import('./../components/app-store/index.vue')['default']
    AppStoreIcon: typeof import('./../components/app-store/app-store-icon.vue')['default']
    AppStoreWindow: typeof import('./../components/app-store/app-store-window.vue')['default']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASpaceCompact: typeof import('ant-design-vue/es')['Compact']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStyleProvider: typeof import('ant-design-vue/es')['StyleProvider']
    Bookmarks: typeof import('./../components/bookmarks/index.vue')['default']
    BookmarksWindow: typeof import('./../components/bookmarks/bookmarks-window.vue')['default']
    IconLocalAppleFilled: typeof import('~icons/local/apple-filled')['default']
    IconLocalBatteryFullOutline: typeof import('~icons/local/battery-full-outline')['default']
    IconLocalClose: typeof import('~icons/local/close')['default']
    IconLocalMacToggle: typeof import('~icons/local/mac-toggle')['default']
    IconLocalSearch: typeof import('~icons/local/search')['default']
    IconLocalWifi: typeof import('~icons/local/wifi')['default']
    ReDock: typeof import('./../components/re-dock/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
