export default [
	{
		children: [
			{
				component: 'notes',
				diyType: '0',
				iconSize: 'icon-size-2x2',
				iconType: 'component',
				id: '23',
				isDelete: '1',
				sortNum: 1,
				title: '备忘录',
				type: '2'
			},
			{
				component: 'weather',
				diyType: '0',
				iconSize: 'icon-size-2x4',
				iconType: 'component',
				id: '19',
				isDelete: '1',
				sortNum: 2,
				title: 'i天气',
				type: '2'
			},
			{
				id: '86ceeb2c-43c2-4d3e-a3e2-9ac03f9b8a36',
				sortNum: 30,
				isDelete: '1',
				type: '2',
				diyType: '1',
				component: '2048',
				iconSize: 'icon-size-2x2',
				title: '2048',
				icon: 'https://file.dhxps.cc/widget/icons/20231020152402A005.svg',
				iconBgC: '#f59563',
				url: 'https://widget.codelife.cc/2048/index.html',
				iconType: 'component'
			},
			{
				id: 'ac953dd4-c518-47c4-af04-20a100a55b42',
				sortNum: 31,
				isDelete: '1',
				type: '2',
				diyType: '1',
				component: 'dino',
				iconSize: 'icon-size-2x2',
				title: '恐龙快跑',
				icon: 'https://file.dhxps.cc/widget/icons/20231020152734A006.svg',
				iconBgC: '#fff',
				url: 'https://widget.codelife.cc/dino/index.html',
				iconType: 'component'
			},
			{
				id: '2393b832-1a41-4bb9-91bf-a2196a5ff248',
				sortNum: 32,
				isDelete: '1',
				type: '2',
				diyType: '1',
				component: 'clock',
				iconSize: 'icon-size-2x2',
				title: '时钟',
				icon: null,
				iconBgC: null,
				url: null,
				iconType: 'component'
			},
			{
				component: 'topsearch',
				diyType: '0',
				iconSize: 'icon-size-2x4',
				iconType: 'component',
				id: '18',
				isDelete: '1',
				sortNum: 3,
				title: '热搜榜',
				type: '2'
			},
			{
				component: 'calendar',
				diyType: '0',
				iconSize: 'icon-size-2x2',
				iconType: 'component',
				id: '20',
				isDelete: '1',
				sortNum: 4,
				title: '日历',
				type: '2'
			},
			{
				component: 'Everything',
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/openeverything.png',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '28',
				isDelete: '1',
				sortNum: 5,
				title: '本地文件搜索',
				type: '2'
			},
			{
				component: 'wallpaper',
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/tools-icon/wallpaper.svg',
				iconSize: 'icon-size-1x1',
				iconType: 'component',
				id: '22',
				isDelete: '1',
				sortNum: 6,
				title: '壁纸',
				type: '2'
			},
			{
				component: 'movieCalendar',
				diyType: '0',
				iconSize: 'icon-size-2x2',
				iconType: 'component',
				id: '21',
				isDelete: '1',
				sortNum: 9,
				title: '电影日历',
				type: '2'
			},
			{
				component: 'games',
				diyType: '0',
				iconSize: 'icon-size-2x2',
				iconType: 'component',
				id: '6174fb6e1b5a48cfa8da6abcdb709104',
				isDelete: '1',
				sortNum: 10,
				title: '小游戏',
				type: '2'
			},
			{
				component: 'countdown',
				config: {
					dayMoney: 1000,
					isWork: true,
					moreList: [1, 2, 3, 4],
					name: '下班倒计时',
					payDay: 10,
					repeatWeek: [8],
					target: 15,
					workTime: ['09:00', '18:00']
				},
				diyType: '0',
				iconSize: 'icon-size-2x4',
				iconType: 'component',
				id: 'fc093f16aa9241878e45b9d34c78df8c',
				isDelete: '1',
				sortNum: 11,
				title: '下班倒计时',
				type: '2'
			},
			{
				component: 'group-widget',
				diyType: '0',
				group: [
					{
						diyType: '0',
						icon: 'https://file.dhxps.cc/itab/icons/bilibili2.svg',
						iconBgC: '#ff5ca1',
						iconSize: 'icon-size-1x1',
						iconType: 'icon',
						id: '61bc4a2410915ef5fe36eb8d',
						isDelete: '1',
						sortNum: 0,
						title: '哔哩哔哩',
						type: '1',
						url: 'https://space.bilibili.com/3546385855023516?spm_id_from=333.337.0.0'
					},
					{
						diyType: '0',
						icon: 'https://file.dhxps.cc/itab/icons/zhihu.svg',
						iconBgC: '#0c6dfe',
						iconSize: 'icon-size-1x1',
						iconType: 'icon',
						id: '60b9ea6fae5a9ba4024b36ec',
						isDelete: '1',
						sortNum: 1,
						title: '知乎',
						type: '1',
						url: 'https://www.zhihu.com/'
					},
					{
						diyType: '0',
						icon: 'https://file.dhxps.cc/itab/icons/weibo.svg',
						iconBgC: '#ffd850',
						iconSize: 'icon-size-1x1',
						iconType: 'icon',
						id: '60b9ea6fae5a9ba4024b36f0',
						isDelete: '1',
						sortNum: 2,
						title: '新浪微博',
						type: '1',
						url: 'https://weibo.com/'
					}
				],
				iconSize: 'icon-size-1x1',
				iconType: 'component',
				id: 'fa9989ddac504efb9ae6fd5a0b678c4a',
				isDelete: '1',
				sortNum: 12,
				title: '资讯',
				type: '3'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/aitaobao.svg',
				iconBgC: '#eb6f2d',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '1',
				isDelete: '1',
				sortNum: 13,
				title: '淘宝',
				type: '1',
				url: 'https://shop.yhyhtech.com/tao.html'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/jd.svg',
				iconBgC: '#ff0000',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '2',
				isDelete: '1',
				sortNum: 13,
				title: '京东商城',
				type: '1',
				url: 'https://u.jd.com/kQYBgzi'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250113220259A001.png',
				iconBgC: '#ff0030',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '4',
				isDelete: '1',
				sortNum: 13,
				title: '天猫新春开门红',
				type: '1',
				url: 'https://s.click.taobao.com/glm6MOs'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/1688.svg',
				iconBgC: '#fd7c11',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '7af85d831a9440498e8667bf834bf667',
				isDelete: '1',
				sortNum: 13,
				title: '阿里巴巴',
				type: '1',
				url: 'https://c.tb.cn/G1.0VnmWe'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/douyu.svg',
				iconBgC: '#ff6a2d',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '7',
				isDelete: '1',
				sortNum: 14,
				title: '斗鱼',
				type: '1',
				url: 'https://www.douyu.com/?dyshid=0-95662d70928dd24a013c8e6b00081601'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20241010214645A001.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'ca6a43dbfc2b4b918252361794607fcf',
				isDelete: '1',
				sortNum: 14,
				title: 'ChatPPT',
				type: '1',
				url: 'https://www.chatppt.cn/?channel=gptbrowser'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/mgtv.svg',
				iconBgC: '#f1711c',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '2e4f4cbeacbf4361b956f7e01cde5205',
				isDelete: '1',
				sortNum: 15,
				title: '芒果TV',
				type: '1',
				url: 'https://www.mgtv.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/iqiyi.svg',
				iconBgC: '#00cc4c',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '11',
				isDelete: '1',
				sortNum: 16,
				title: '爱奇艺',
				type: '1',
				url: 'https://www.iqiyi.com/?vfm=m_577_tjP&fv=8bead5cba030cd96'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/music163.svg',
				iconBgC: '#fe1816',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '12',
				isDelete: '1',
				sortNum: 18,
				title: '网易云音乐',
				type: '1',
				url: 'https://music.163.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20231206154651A001.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'acbbd144151e4e508067389ecaffb40d',
				isDelete: '1',
				sortNum: 19,
				title: '启源数据恢复',
				type: '1',
				url: 'https://www.qymaster.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/xiangya.png',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '24',
				isDelete: '1',
				sortNum: 20,
				title: '象牙装机',
				type: '1',
				url: 'http://www.ixiangya.net/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250106190223A001.webp',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '68a5c89ad36542ccb4b251bd1ed7916b',
				isDelete: '1',
				sortNum: 22,
				title: '摸鱼小游戏',
				type: '1',
				url: 'https://www.17yoo.cn/ztf/5B739316?pid=PIDUQG3vfXzR'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20231225142701A003.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '245f319a69864480b6f2b01c01ff3091',
				isDelete: '1',
				sortNum: 27,
				title: '豆包-你的AI朋友',
				type: '1',
				url: 'https://shop.yhyhtech.com/ai.html'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/60b9ea92ae5a9ba4024b37e9.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9476142958bd495c84027be340b47a85',
				isDelete: '1',
				sortNum: 28,
				title: 'hao123导航',
				type: '1',
				url: 'https://hao.yhyhtech.com'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/baidu.svg',
				iconBgC: '#346efd',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '6',
				isDelete: '1',
				sortNum: 29,
				title: '百度',
				type: '1',
				url: 'https://www.baidu.com/?tn=25017023_13_dg&ch=1'
			},
			{
				component: 'novice-guide',
				diyType: '0',
				iconSize: 'icon-size-1x1',
				iconType: 'component',
				id: '189d7e37-cc61-4438-94ee-03eb630f71df',
				isDelete: '1',
				sortNum: 9,
				title: '新手引导',
				type: '2'
			},
			{
				component: 'game-video',
				diyType: '0',
				iconSize: 'icon-size-2x4',
				iconType: 'component',
				id: 'dcaad818-508c-46ab-9568-56750b59c130',
				isDelete: '1',
				sortNum: 9,
				title: '游戏视频',
				type: '2'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/setting.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '27',
				isDelete: '0',
				sortNum: 30,
				title: '设置',
				type: '1',
				url: 'itab://setting'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/add.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '999',
				isDelete: '0',
				sortNum: 31,
				title: '添加图标',
				type: '1',
				url: 'itab://add'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/add.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'aksjflksdnfkjs',
				isDelete: '0',
				sortNum: 31,
				title: '添加图标',
				type: '1',
				url: 'itab://add'
			}
		],
		ckVer: null,
		icon: 'https://file.dhxps.cc/nav/icon/home.svg',
		id: '1',
		isDelete: '1',
		name: '主页',
		sortNum: 1
	},
	{
		children: [
			{
				component: 'stmgame',
				diyType: '0',
				iconSize: 'icon-size-4x7',
				iconType: 'component',
				id: '860bb7e83cd145d78c4316e7b6ff3626',
				isDelete: '1',
				sortNum: 1,
				title: '游戏折扣',
				type: '2'
			},
			{
				component: 'playtogether',
				diyType: '0',
				iconSize: 'icon-size-2x4',
				iconType: 'component',
				id: 'eff87ee26bd94afb81d6dbb86cd1c618',
				isDelete: '1',
				sortNum: 2,
				title: '即玩游戏',
				type: '2'
			},
			{
				component: 'gamenews',
				diyType: '0',
				iconSize: 'icon-size-2x2',
				iconType: 'component',
				id: 'ce7879de54664f5ba5537c3e28de5cce',
				isDelete: '1',
				sortNum: 3,
				title: '游戏资讯',
				type: '2'
			},
			{
				component: 'games',
				diyType: '0',
				iconSize: 'icon-size-2x2',
				iconType: 'component',
				id: '0e14c95b21404d33b3e6a974184e608a',
				isDelete: '1',
				sortNum: 4,
				title: '小游戏',
				type: '2'
			},
			{
				component: 'tetris',
				diyType: '0',
				iconSize: 'icon-size-7x4',
				iconType: 'component',
				id: '53a23s5k3f5n77sa54sfsd485kd1ng',
				isDelete: '1',
				sortNum: 3,
				title: '俄罗斯方块',
				type: '2'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250106190223A001.webp',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'eba5d7da884948358467b9462ffa3b91',
				isDelete: '1',
				sortNum: 5,
				title: '摸鱼小游戏',
				type: '1',
				url: 'https://www.17yoo.cn/ztf/5B739316?pid=PIDUQG3vfXzR'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121171028A001.jpg',
				iconBgC: '#171d29',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '5e0b8b1ae2ab4f7b8bc575438a283a44',
				isDelete: '1',
				sortNum: 6,
				title: 'Steambig',
				type: '1',
				url: 'https://front.steambig.com/game?channel=ww'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/huya.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'faac3e40d2eb442b80b335c17aaf6fc8',
				isDelete: '1',
				sortNum: 7,
				title: '虎牙直播',
				type: '1',
				url: 'http://www.huya.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/douyu.svg',
				iconBgC: '#ff6a2d',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '40e3781343ee48cc8ffb7b2507aa8478',
				isDelete: '1',
				sortNum: 8,
				title: '斗鱼',
				type: '1',
				url: 'https://www.douyu.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/4399.svg',
				iconBgC: '#f19425',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '92717913e1c249c593cacf0ea5fff2aa',
				isDelete: '1',
				sortNum: 9,
				title: '4399小游戏',
				type: '1',
				url: 'https://www.4399.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/bilibili2.svg',
				iconBgC: '#ff5ca1',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '867ed207500942709ad210dfaf8a0d72',
				isDelete: '1',
				sortNum: 10,
				title: '哔哩哔哩',
				type: '1',
				url: 'https://space.bilibili.com/3546385855023516?spm_id_from=333.337.0.0'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/www.yikm.net.svg',
				iconBgC: '#1499b5',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'a10ac77d1c06418bbb7d21cbee4e7a3c',
				isDelete: '1',
				sortNum: 11,
				title: '小霸王',
				type: '1',
				url: 'https://www.yikm.net/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121171500A003.png',
				iconBgC: '#ffdd00',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '777cedbc680f4bada4910d638fe8b842',
				isDelete: '1',
				sortNum: 12,
				title: '带带陪玩',
				type: '1',
				url: 'https://play.daidaicp.com/index'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/www.huashuimoyu.com.svg',
				iconBgC: '#87b362',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '5d792589a06741d0af01e65e49741952',
				isDelete: '1',
				sortNum: 13,
				title: '划水摸鱼',
				type: '1',
				url: 'https://www.huashuimoyu.com'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121180710A017.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '7a9285c158c14aa6b90af760dbb0480d',
				isDelete: '1',
				sortNum: 14,
				title: 'Flash保存计划',
				type: '1',
				url: 'https://flash.homes/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121175451A015.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9652eebd3ca04b86bab815b3c57f1853',
				isDelete: '1',
				sortNum: 15,
				title: 'YORG塔防',
				type: '1',
				url: 'https://yorg.io/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121172318A005.png',
				iconBgC: '#42ce9b',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '24f8d92e77414b928d5f7cb77d0e94b1',
				isDelete: '1',
				sortNum: 16,
				title: '熊猫频道',
				type: '1',
				url: 'https://www.ipanda.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121173003A007.jpg',
				iconBgC: '#000000',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '98433a20d82947d0bff01f04ded4b10e',
				isDelete: '1',
				sortNum: 17,
				title: '俄罗斯方块',
				type: '1',
				url: 'https://chvin.github.io/react-tetris/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121180848A019.png',
				iconBgC: '#ff696a',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'b42ba6e24fc6410795ef7549780abcd5',
				isDelete: '1',
				sortNum: 18,
				title: '奇趣网站收藏家',
				type: '1',
				url: 'https://fuun.fun/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121173249A009.png',
				iconBgC: '#4b3c5a',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9ccbe20b46174f41886a581f31496d0f',
				isDelete: '1',
				sortNum: 19,
				title: '这里有猫',
				type: '1',
				url: 'https://m.niucodata.com/cat/cat.php'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121174032A011.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '07e73353c11d4acc98c5cd38122f61bf',
				isDelete: '1',
				sortNum: 20,
				title: 'Poki免费游戏',
				type: '1',
				url: 'https://poki.com/zh'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121174642A013.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'd5c1c2a77b00447f8ee366439aa33ef9',
				isDelete: '1',
				sortNum: 21,
				title: '红色警戒-网页版',
				type: '1',
				url: 'https://ra2web.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121181030A021.png',
				iconBgC: '#020305',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '057fbb27f1ce4a63a1674546621c43e6',
				isDelete: '1',
				sortNum: 22,
				title: 'Su7',
				type: '1',
				url: 'https://gamemcu.com/su7/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250121181146A023.png',
				iconBgC: '#88cccc',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '6fc882b72a824e0185aae7bb6a5df197',
				isDelete: '1',
				sortNum: 23,
				title: 'Mikutap',
				type: '1',
				url: 'https://aidn.jp/mikutap/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/taptap.svg',
				iconBgC: '#24becb',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '93992a28ac0e4b879e69b943b93022ff',
				isDelete: '1',
				sortNum: 24,
				title: 'TapTap',
				type: '1',
				url: 'https://www.taptap.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20250217151359A002.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '89502108ae6742ae8dc240f3ea4e3e0a',
				isDelete: '1',
				sortNum: 25,
				title: '人生重开模拟器',
				type: '1',
				url: 'https://liferestart.syaro.io/public/index.html'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/add.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '88ffe73fa1384697ad2cc00f013762e3',
				isDelete: '1',
				sortNum: 26,
				title: '添加图标',
				type: '1',
				url: 'itab://add'
			}
		],
		ckVer: null,
		icon: 'https://file.dhxps.cc/nav/icon/recreation.svg',
		id: 'bd4368224cf7427aadfd616d53cf80eb',
		isDelete: '1',
		name: '游戏',
		sortNum: 2
	},
	{
		children: [
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/apifoxcn.svg',
				iconBgC: '#f4425f',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'xLiON51K5',
				isDelete: '1',
				sortNum: 1,
				title: 'Apifox',
				type: '1',
				url: 'https://apifox.cn/a1itabweb'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/github.svg',
				iconBgC: '#000',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'CZHjnJIMB',
				isDelete: '1',
				sortNum: 2,
				title: 'GitHub',
				type: '1',
				url: 'https://github.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/v2ex.svg',
				iconBgC: '#222222',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'sfPX-WRi0',
				isDelete: '1',
				sortNum: 3,
				title: 'V2EX',
				type: '1',
				url: 'http://www.v2ex.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/react.svg',
				iconBgC: '#27333b',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'zsTvF1WI3',
				isDelete: '1',
				sortNum: 4,
				title: 'React',
				type: '1',
				url: 'https://reactjs.org/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/mrjokersince-java.svg',
				iconBgC: '#1c1c1c',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '8c76d96090dc41bd82af3595af458125',
				isDelete: '1',
				sortNum: 5,
				title: 'Java 学习笔记',
				type: '1',
				url: 'https://mrjokersince1997.github.io/My-Notes/#/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/gitee.svg',
				iconBgC: '#bb2124',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'yQv_IiTzL',
				isDelete: '1',
				sortNum: 6,
				title: '码云Gitee',
				type: '1',
				url: 'https://gitee.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/csdn.svg',
				iconBgC: '#cc001b',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'NKfU43cp6',
				isDelete: '1',
				sortNum: 7,
				title: 'CSDN',
				type: '1',
				url: 'https://www.csdn.net/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/w3school.svg',
				iconBgC: '#cc3333',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9ivZt9a2i',
				isDelete: '1',
				sortNum: 8,
				title: 'w3school在线教程',
				type: '1',
				url: 'http://www.w3school.com.cn'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/stackoverflow.svg',
				iconBgC: '#444444',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'omCrX5KHJ',
				isDelete: '1',
				sortNum: 9,
				title: 'Stack Overflow',
				type: '1',
				url: 'https://stackoverflow.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/juejin.svg',
				iconBgC: '#0984fe',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'fa9f43c9542141ceb76f7268d08c9153',
				isDelete: '1',
				sortNum: 10,
				title: '掘金',
				type: '1',
				url: 'https://juejin.cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/leetcode.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '74611d2409e1426fbcc98e5941a99301',
				isDelete: '1',
				sortNum: 11,
				title: '力扣',
				type: '1',
				url: 'https://leetcode.cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/vuejs.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '8925dd96434b4108a8e7c2ea803a0d6c',
				isDelete: '1',
				sortNum: 12,
				title: 'Vue2中文文档',
				type: '1',
				url: 'https://cn.vuejs.org/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/arco-design.svg',
				iconBgC: '#fdfef7',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'a38f17b6ffa44efa9c170c54615abf1a',
				isDelete: '1',
				sortNum: 13,
				title: 'Arco Design',
				type: '1',
				url: 'https://arco.design'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/ant-design-vue.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '793e6be108994856996928524d535c59',
				isDelete: '1',
				sortNum: 14,
				title: 'Ant Design Vue',
				type: '1',
				url: 'https://www.antdv.com/docs/vue/introduce-cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/oschina.svg',
				iconBgC: '#34b960',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9b6cdedbdce94355acc8284d2d4a08f1',
				isDelete: '1',
				sortNum: 15,
				title: '开源中国',
				type: '1',
				url: 'http://www.oschina.net/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/asiayun.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'e28b0cc614cc4c48a84716cbfcc8ee84',
				isDelete: '1',
				sortNum: 16,
				title: '亚云',
				type: '1',
				url: 'https://www.asiayun.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/geekbang.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '2b864f67c179473888c612955aea500c',
				isDelete: '1',
				sortNum: 17,
				title: '极客时间',
				type: '1',
				url: 'https://time.geekbang.org'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/kaifa.baidu.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '183584ede36940aeb4e7fa999141554d',
				isDelete: '1',
				sortNum: 18,
				title: '开发者搜索',
				type: '1',
				url: 'https://kaifa.baidu.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/60b9ef46ae5a9ba4024b47b3.png',
				iconBgC: '#e53122',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'f86db7222b0c41a0a30f95cd83eb7a0e',
				isDelete: '1',
				sortNum: 19,
				title: 'Java 8 API',
				type: '1',
				url: 'https://docs.oracle.com/javase/8/docs/api/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/60b9eb13ae5a9ba4024b3a2a.png',
				iconBgC: '#a24637',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'ac48eb5fa3944b098bc06e8a399f2cc3',
				isDelete: '1',
				sortNum: 20,
				title: '脚本之家',
				type: '1',
				url: 'http://www.jb51.net/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/add.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '15e21118746f438caf79c91183ea3054',
				isDelete: '1',
				sortNum: 21,
				title: '添加图标',
				type: '1',
				url: 'itab://add'
			}
		],
		ckVer: null,
		icon: 'https://file.dhxps.cc/nav/icon/consult.svg',
		id: '3',
		isDelete: '1',
		name: '编程',
		sortNum: 3
	},
	{
		children: [
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/gaoding.svg',
				iconBgC: '#0050ff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '3NjEiwNGO',
				isDelete: '1',
				sortNum: 1,
				title: '稿定设计',
				type: '1',
				url: 'https://www.gaoding.com/utms/ba46f32f055a48aab63ee74f15281593'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/jsdesign.svg',
				iconBgC: '#cf3d35',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '5kGk9TzkRam-a',
				isDelete: '1',
				sortNum: 2,
				title: '即时设计',
				type: '1',
				url: 'https://js.design?source=itab&plan=2'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/huaban.svg',
				iconBgC: '#ea2936',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'v_xMvU7V_',
				isDelete: '1',
				sortNum: 3,
				title: '花瓣',
				type: '1',
				url: 'http://huaban.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/zcool.svg',
				iconBgC: '#e6be1c',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'raBGdwOvo',
				isDelete: '1',
				sortNum: 4,
				title: '站酷',
				type: '1',
				url: 'https://www.zcool.com.cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/dribbble.svg',
				iconBgC: '#f23f71',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'qW3jSNLWy',
				isDelete: '1',
				sortNum: 5,
				title: 'Dribbble',
				type: '1',
				url: 'https://dribbble.com'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/60b9f0baae5a9ba4024b4c49.png',
				iconBgC: '#000000',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'oTmQeJ71f',
				isDelete: '1',
				sortNum: 6,
				title: '绘画艺术',
				type: '1',
				url: 'http://www.qijishow.com/Brand/Brand23/index.htm'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/bigbigwork.svg',
				iconBgC: '#ff4d4d',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '6893f9bee1aa4af09bd5445893230cff',
				isDelete: '1',
				sortNum: 7,
				title: '大作免费版权图片',
				type: '1',
				url: 'https://www.bigbigwork.com/?from=itab'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/nipic.svg',
				iconBgC: '#dd137b',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '3e90d944b4a240fc8a379bf958282178',
				isDelete: '1',
				sortNum: 8,
				title: '昵图网',
				type: '1',
				url: 'https://www.nipic.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/uidesigndaily.svg',
				iconBgC: '#fafefe',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'dc2354ec5885450093d762f7f87a2e62',
				isDelete: '1',
				sortNum: 9,
				title: '每日 ui 设计',
				type: '1',
				url: 'https://uidesigndaily.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/wallhave.svg',
				iconBgC: '#0c4061',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '238b1e64b9054f268215c89542c97517',
				isDelete: '1',
				sortNum: 10,
				title: 'Wallhaven',
				type: '1',
				url: 'https://wallhaven.cc/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/unsplash.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '1e2ead35f56941dabc1834fa2300d15e',
				isDelete: '1',
				sortNum: 11,
				title: 'Unsplash',
				type: '1',
				url: 'https://unsplash.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/60b9eba2ae5a9ba4024b3bfc.png',
				iconBgC: '#cde7f0',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '04db0fe80db446df846c34957756a2cb',
				isDelete: '1',
				sortNum: 12,
				title: 'TinyPNG',
				type: '1',
				url: 'https://tinypng.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/5ad463a9c251950593a11cdd.png',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '4b88bb0a8c514e65a02cb759a2325b52',
				isDelete: '1',
				sortNum: 13,
				title: '柠檬轻搜索 - 干净、安全、可信任的小清新轻搜索导航',
				type: '1',
				url: 'http://www.llemon.cn'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/iconfont.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '2f41240a76ee48ecbe0f530a20eec369',
				isDelete: '1',
				sortNum: 14,
				title: 'Iconfont',
				type: '1',
				url: 'https://www.iconfont.cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/lusun.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '18c2bf8a3d7c46d39c588598a6acd86a',
				isDelete: '1',
				sortNum: 15,
				title: '芦笋 - 极简录屏&云端存储&一键分享',
				type: '1',
				url: 'https://lusun.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/zhongguose.com.svg',
				iconBgC: '#dadada',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9ba9853d734d440187eca690505e055b',
				isDelete: '1',
				sortNum: 16,
				title: '中国色',
				type: '1',
				url: 'http://zhongguose.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/58pic.svg',
				iconBgC: '#00a46b',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '81a7bb171dbe4d3793f06c071f4bc020',
				isDelete: '1',
				sortNum: 17,
				title: '千图网',
				type: '1',
				url: 'https://www.58pic.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/ibaotu.svg',
				iconBgC: '#fff5c8',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '6335e5cea1094e6db1bf823465bb1909',
				isDelete: '1',
				sortNum: 18,
				title: '包图网',
				type: '1',
				url: 'https://ibaotu.com/?spm=itab'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/qijishow.svg',
				iconBgC: '#122441',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'f1b507fa7c194d50966a2e933a3b267b',
				isDelete: '1',
				sortNum: 19,
				title: '奇迹秀',
				type: '1',
				url: 'http://www.qijishow.com/down/index.html'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/60b9ed6aae5a9ba4024b41b0.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'a9e34c43824943cda74fc87164594164',
				isDelete: '1',
				sortNum: 20,
				title: '[字由] 字体识别',
				type: '1',
				url: 'https://www.hellofont.cn/font-ai'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/add.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'd0c1869740ae4d81a20f35776f0a2bed',
				isDelete: '1',
				sortNum: 21,
				title: '添加图标',
				type: '1',
				url: 'itab://add'
			}
		],
		ckVer: null,
		icon: 'https://file.dhxps.cc/nav/icon/picture.svg',
		id: '4',
		isDelete: '1',
		name: '设计',
		sortNum: 4
	},
	{
		children: [
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/woshipm.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '4IM79snuL',
				isDelete: '1',
				sortNum: 1,
				title: '人人都是产品经理',
				type: '1',
				url: 'http://www.woshipm.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/flowus.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'vqZCrDh6zad',
				isDelete: '1',
				sortNum: 2,
				title: 'FlowUs',
				type: '1',
				url: 'https://flowus.cn/?promotionChannel=WZ_it_01'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/notion.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'vqZCrDh6z',
				isDelete: '1',
				sortNum: 3,
				title: 'Notion',
				type: '1',
				url: 'https://www.notion.so/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/utools.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '-wDKDVcMeU3Ptykw-F0aF',
				isDelete: '1',
				sortNum: 4,
				title: 'uTools',
				type: '1',
				url: 'https://u.tools/?from=itab'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/xiezuocat.com.svg',
				iconBgC: '#fefefe',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'bd4b1f2e0c6d4988a5cecf519d2dbae4',
				isDelete: '1',
				sortNum: 5,
				title: '秘塔写作猫',
				type: '1',
				url: 'https://xiezuocat.com/#/?s=itab'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/dida365.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '68740985d15d44528c1627678eb9a024',
				isDelete: '1',
				sortNum: 6,
				title: '滴答清单',
				type: '1',
				url: 'https://www.dida365.com/webapp'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/iconfont.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'fe1a7a9ffc8e4ade84150f666d8eb182',
				isDelete: '1',
				sortNum: 7,
				title: 'Iconfont',
				type: '1',
				url: 'https://www.iconfont.cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/36kr.svg',
				iconBgC: '#1380d8',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'c870c12a387e4e42a55c05577211bebe',
				isDelete: '1',
				sortNum: 8,
				title: '36氪',
				type: '1',
				url: 'http://www.36kr.com'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/zhixi.svg',
				iconBgC: '#4dec7c',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '52a72bc501e44d3d847b4cd173fc252c',
				isDelete: '1',
				sortNum: 9,
				title: '知犀思维导图',
				type: '1',
				url: 'https://www.zhixi.com/space?src=itab'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/cowtransfer.svg',
				iconBgC: '#ffd95a',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9bdafae9d2734ae79c44983a0cef13e3',
				isDelete: '1',
				sortNum: 10,
				title: '奶牛快传',
				type: '1',
				url: 'https://datayi.cn/w/EoZAmJyP'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/shutu.cn.webp',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'd5cdb11c72454451a5319d3faef31da2',
				isDelete: '1',
				sortNum: 11,
				title: 'AI思维导图',
				type: '1',
				url: 'https://shutu.cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/ibiling.cn.webp',
				iconBgC: '#00b178',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'a2633fa8de9e4d279db2660d0bc2f459',
				isDelete: '1',
				sortNum: 12,
				title: '免费AI写作',
				type: '1',
				url: 'https://ibiling.cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/shimo.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '1e87a815316642a9a9bc63f2dea2539e',
				isDelete: '1',
				sortNum: 13,
				title: '石墨',
				type: '1',
				url: 'https://shimo.im/desktop'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/20230919111823A002.svg',
				iconBgC: '#d7191a',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '2c8e49c05fa04abdb357e7977df4b5c0',
				isDelete: '1',
				sortNum: 14,
				title: '少数派',
				type: '1',
				url: 'https://sspai.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/crxsoso.com.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9a930fab5001469f90d83e075e486003',
				isDelete: '1',
				sortNum: 15,
				title: '扩展搜搜',
				type: '1',
				url: 'https://www.crxsoso.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/islide.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '01d7b7ffd468421a8192468a1dd18cb0',
				isDelete: '1',
				sortNum: 16,
				title: 'iSlide PPT神器',
				type: '1',
				url: 'https://dwz.islide.cc/itab'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/boardmix.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'db5379d8d5994ffcbcbeaf9f6c039186',
				isDelete: '1',
				sortNum: 17,
				title: 'boardmix白板',
				type: '1',
				url: 'https://boardmix.cn/mindmapping/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/abcdpdf.svg',
				iconBgC: '#28364d',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '600b1e10549d42d392eb7d64cd286da6',
				isDelete: '1',
				sortNum: 18,
				title: 'ABCD PDF',
				type: '1',
				url: 'https://abcdpdf.com/zh-cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/axmaxcn.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '6e3bfccad67140e292b229b8f2c7a99f',
				isDelete: '1',
				sortNum: 19,
				title: '原型托管',
				type: '1',
				url: 'https://axmax.cn'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/www.kdocs.cn_latest.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '940c520f9d664644a22ff37f8bccb1d0',
				isDelete: '1',
				sortNum: 20,
				title: '金山文档',
				type: '1',
				url: 'https://www.kdocs.cn/latest'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/add.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'cc45dcfe23a54e718bfafddb65ee4f3f',
				isDelete: '1',
				sortNum: 21,
				title: '添加图标',
				type: '1',
				url: 'itab://add'
			}
		],
		ckVer: null,
		icon: 'https://file.dhxps.cc/nav/icon/product.svg',
		id: '5',
		isDelete: '1',
		name: '产品',
		sortNum: 5
	},
	{
		children: [
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/weibo.svg',
				iconBgC: '#ffd850',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '570f553ec69342b4914ca17c35605bc1',
				isDelete: '1',
				sortNum: 2,
				title: '新浪微博',
				type: '1',
				url: 'http://weibo.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/iqiyi.svg',
				iconBgC: '#00cc4c',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9e6f9b57ae9a4101b6a1963e0b1cc0d8',
				isDelete: '1',
				sortNum: 3,
				title: '爱奇艺',
				type: '1',
				url: 'https://www.iqiyi.com/?vfm=f_432_dhm&fv=8648154ddd63e0af'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/youku.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '90d9bb5ae68248e28abcd825eca750ca',
				isDelete: '1',
				sortNum: 4,
				title: '优酷',
				type: '1',
				url: 'https://www.youku.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/qqvideo.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '93248efab086495796de44e5451bb70b',
				isDelete: '1',
				sortNum: 5,
				title: '腾讯视频',
				type: '1',
				url: 'http://v.qq.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/zhihu.svg',
				iconBgC: '#0c6dfe',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '61ea85b88f65402bbfec9c3b028344e0',
				isDelete: '1',
				sortNum: 6,
				title: '知乎',
				type: '1',
				url: 'https://www.zhihu.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/steam.svg',
				iconBgC: '#000000',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9ba5f043bfd24489b0d8385d44993980',
				isDelete: '1',
				sortNum: 7,
				title: 'Steam',
				type: '1',
				url: 'https://store.steampowered.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/douyin.svg',
				iconBgC: '#1c0b1a',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'f520fe03fc6a41978559ef464338336f',
				isDelete: '1',
				sortNum: 8,
				title: '抖音',
				type: '1',
				url: 'https://www.douyin.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/meiriyiwen.svg',
				iconBgC: '#29505b',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '66565c0fbed74a05846ca39abfadc15d',
				isDelete: '1',
				sortNum: 9,
				title: '每日一文',
				type: '1',
				url: 'http://meiriyiwen.com'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/okjike.svg',
				iconBgC: '#f3db2b',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '050cf5ef65cf4da68d2f5eb3b70baf5b',
				isDelete: '1',
				sortNum: 10,
				title: '即刻网页版',
				type: '1',
				url: 'https://web.okjike.com'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/4399.svg',
				iconBgC: '#f19425',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'b31f665773704bca8461f7835e3e5091',
				isDelete: '1',
				sortNum: 11,
				title: '4399小游戏',
				type: '1',
				url: 'https://www.4399.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/bilibili2.svg',
				iconBgC: '#ff5ca1',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '2b01f25743964bad9c30eded0e1b76f4',
				isDelete: '1',
				sortNum: 12,
				title: '哔哩哔哩',
				type: '1',
				url: 'https://space.bilibili.com/3546385855023516?spm_id_from=333.337.0.0'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/www.yikm.net.svg',
				iconBgC: '#1499b5',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'b23cf2fe9e8a42eab1cc82b30c0c07bf',
				isDelete: '1',
				sortNum: 13,
				title: '小霸王',
				type: '1',
				url: 'https://www.yikm.net/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/huya.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '31b911a85b97496d8262c6277ae9cc82',
				isDelete: '1',
				sortNum: 14,
				title: '虎牙直播',
				type: '1',
				url: 'http://www.huya.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/douyu.svg',
				iconBgC: '#ff6a2d',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'fadb8d9dc5ee48a89de9e02bb05513dd',
				isDelete: '1',
				sortNum: 15,
				title: '斗鱼',
				type: '1',
				url: 'https://www.douyu.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/59f86644d8bf9277d70b3f60.png',
				iconBgC: '#1abc9c',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'b8a8c10fadce4502b80ff97fd3123bf1',
				isDelete: '1',
				sortNum: 16,
				title: '番组放送',
				type: '1',
				url: 'https://bgmlist.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/rebang.today.png',
				iconBgC: '#165dff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'fdd09655f1064c71a0dd3214452c1d1c',
				isDelete: '1',
				sortNum: 17,
				title: '今日热榜',
				type: '1',
				url: 'https://rebang.today/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/fanqienovel.svg',
				iconBgC: '#fff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'f8f626c852dc4629858557b8d399340d',
				isDelete: '1',
				sortNum: 18,
				title: '番茄小说网',
				type: '1',
				url: 'https://fanqienovel.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/xiaozhongjishu.com.png',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'fc0fcb7f46f6428cbc7fd4ecf69ad87e',
				isDelete: '1',
				sortNum: 20,
				title: '小众技术资源库',
				type: '1',
				url: 'https://www.xiaozhongjishu.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/add.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '4e4d38ae94484af4b0698546d3f7a97d',
				isDelete: '1',
				sortNum: 21,
				title: '添加图标',
				type: '1',
				url: 'itab://add'
			}
		],
		ckVer: null,
		icon: 'https://file.dhxps.cc/nav/icon/leaf.svg',
		id: '6',
		isDelete: '1',
		name: '摸鱼',
		sortNum: 6
	},
	{
		children: [
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/openmao.panchuang.net.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '5b22ba6d599547eaaa5bf6c5731acfa8',
				isDelete: '1',
				sortNum: 1,
				title: '开放猫论文助手',
				type: '1',
				url: 'https://paper.openmao.cn/openmao/#/academic-paper/create'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/xiezuocat.com.svg',
				iconBgC: '#fefefe',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '50d5d0e6a3a24bb3bdeb80c6d25c5e39',
				isDelete: '1',
				sortNum: 2,
				title: '秘塔写作猫',
				type: '1',
				url: 'https://xiezuocat.com/#/?s=itab'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/writingo.net.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '7a60b7792e89420a85b052ca7172695a',
				isDelete: '1',
				sortNum: 3,
				title: '火山写作',
				type: '1',
				url: 'https://www.writingo.net/document?source=itab'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/js-design-ai.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9e1af3430f7a4f74b35ae79f9c01830d',
				isDelete: '1',
				sortNum: 4,
				title: '即时AI',
				type: '1',
				url: 'https://js.design/ai?source=itab&plan=ai'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/yige.baidu.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '9adb7df950e449a783dc4b9ae8f8ebe8',
				isDelete: '1',
				sortNum: 5,
				title: '文心一格',
				type: '1',
				url: 'https://yige.baidu.com'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/baidu.svg',
				iconBgC: '#0050ff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '6c2e1be937f346abb0061abc62fbfe2c',
				isDelete: '1',
				sortNum: 6,
				title: '稿定AI做图',
				type: '1',
				url: 'https://www.gaoding.com/utms/ba46f32f055a48aab63ee74f15281593'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/shutu.cn.webp',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'a864320166f24c518b0c9ff9b58e77eb',
				isDelete: '1',
				sortNum: 7,
				title: 'AI思维导图',
				type: '1',
				url: 'https://shutu.cn/?from=itab'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/k986.png',
				iconBgC: '#141416',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'cce1a4984da14c419780ce5e436a44de',
				isDelete: '1',
				sortNum: 8,
				title: 'Ai作图',
				type: '1',
				url: 'https://k986.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/giiso.png',
				iconBgC: '#444444',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '50a15ed8f23d44a7bb4c5d991dd09c45',
				isDelete: '1',
				sortNum: 9,
				title: 'Giiso写作机器人',
				type: '1',
				url: 'https://www.giiso.com/#/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/feishufeishu.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '8213723551374279bdc1dc6925d2244a',
				isDelete: '1',
				sortNum: 10,
				title: '飞书妙记',
				type: '1',
				url: 'https://www.feishu.cn/product/minutes'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/aigc.wondershare.cn.svg',
				iconBgC: '#12142f',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'ae01ee7892b74653972134f9a1dc83af',
				isDelete: '1',
				sortNum: 11,
				title: '万兴爱画',
				type: '1',
				url: 'https://aigc.wondershare.cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/wenxin.baidu.png',
				iconBgC: '#383aee',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'd2f14122392041a183aaa3fdcda0a270',
				isDelete: '1',
				sortNum: 12,
				title: '百度创意应用',
				type: '1',
				url: 'https://wenxin.baidu.com/younger/creativeSpace'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/zenvideo.qq.com.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '09e299bb68384c099e16b169e0ae233e',
				isDelete: '1',
				sortNum: 13,
				title: '腾讯智影',
				type: '1',
				url: 'https://zenvideo.qq.com/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/chatbox.cool.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '01408121739d4243b91031666ac3019f',
				isDelete: '1',
				sortNum: 14,
				title: '集智魔方',
				type: '1',
				url: 'http://www.chatbox.cool/#/home'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/4c9b40.png',
				iconBgC: '#000000',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: 'b5c86cf65603426199985eca6b9ceb8c',
				isDelete: '1',
				sortNum: 15,
				title: '百度智能创作',
				type: '1',
				url: 'https://ai.baidu.com/creativity/main/workbench'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/pm-ai.cn.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '0ba1f04e6bd84cce95b45ea14d4c81fc',
				isDelete: '1',
				sortNum: 16,
				title: '产品经理AI助手',
				type: '1',
				url: 'https://www.pm-ai.cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/ibiling.cn.webp',
				iconBgC: '#00b178',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '526602bf9df249018d267757fc73558c',
				isDelete: '1',
				sortNum: 17,
				title: '免费AI写作',
				type: '1',
				url: 'https://ibiling.cn/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/monica.im.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '3a15cfc3d7a546a88feaeadb8ceaff41',
				isDelete: '1',
				sortNum: 18,
				title: '免费ChatAI',
				type: '1',
				url: 'https://monica.im/'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/top-ai.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '834eff6b516a4cfcae543d0918336283',
				isDelete: '1',
				sortNum: 19,
				title: 'Top.AI',
				type: '1',
				url: 'https://topd.tencent.com/ai'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/tingwu.aliyun.png',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '305149ef289c41d493349a53f4560457',
				isDelete: '1',
				sortNum: 20,
				title: '通义听悟',
				type: '1',
				url: 'https://tingwu.aliyun.com/?cid=38'
			},
			{
				diyType: '0',
				icon: 'https://file.dhxps.cc/itab/icons/add.svg',
				iconBgC: '#ffffff',
				iconSize: 'icon-size-1x1',
				iconType: 'icon',
				id: '5643d278061047bd9febd60983204301',
				isDelete: '1',
				sortNum: 21,
				title: '添加图标',
				type: '1',
				url: 'itab://add'
			}
		],
		ckVer: null,
		icon: 'https://file.dhxps.cc/nav/icon/technology.svg',
		id: '7',
		isDelete: '1',
		name: 'AI',
		sortNum: 7
	},
	{
		id: '2',
		iconId: 16,
		name: '资讯',
		icon: 'https://file.dhxps.cc/nav/icon/astronomy.svg',
		children: null,
		isDelete: '1'
	}
]
