import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync
} from 'node:fs'
import path from 'node:path'

import { logger } from '../../../core/logger.ts'
import { assertPath, ensureDir, writeUtf8NoBom } from '../infra/fs.ts'
import {
  CLEAN_WEBUI_NAMES,
  WEBUI_SYNC_SKIP_EXTENSIONS,
  WEBUI_SYNC_SKIP_NAMES
} from '../infra/paths.ts'
import type { BrowserAction, BrowserContext } from '../types.ts'

const SyncAction: BrowserAction = {
  name: 'sync',
  description: '5. 把 WebUI 构建产物同步进 overlay / 源码树',
  register(parent, ctx) {
    parent
      .command(this.name)
      .description(this.description)
      .action(function () {
        runSync(ctx)
      })
  }
}

function isSkippedName(name: string): boolean {
  if ((WEBUI_SYNC_SKIP_NAMES as readonly string[]).includes(name)) {
    return true
  }
  const lower = name.toLowerCase()
  return (WEBUI_SYNC_SKIP_EXTENSIONS as readonly string[]).some(function (ext) {
    return lower.endsWith(ext)
  })
}

function findDistRelativeFiles(root: string): string[] {
  const rootFull = path.resolve(root)
  const files: string[] = []

  function walk(dir: string): void {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (isSkippedName(entry.name)) {
        continue
      }
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        walk(full)
        continue
      }
      const rel = full.slice(rootFull.length + 1).replace(/\\/g, '/')
      files.push(rel)
    }
  }

  walk(rootFull)
  return files.sort()
}

function writeResourcesBuildGn(filePath: string, inputFiles: string[]): void {
  if (inputFiles.length === 0) {
    throw new Error('[browser] No input files for BUILD.gn')
  }
  const quoted = inputFiles.map(function (f) {
    return `    "${f}",`
  })
  const content = `# Copyright 2026 The i-thinking Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# GENERATED by pnpm command browser sync - do not hand-edit input_files.
# Source: apps/browser/dist (Vite outDir).

import("//tools/grit/grit_rule.gni")
import("//ui/webui/resources/tools/generate_grd.gni")

generate_grd("build_grd") {
  grd_prefix = "i_thinking"
  out_grd = "$target_gen_dir/i_thinking_resources.grd"
  input_files = [
${quoted.join('\n')}
  ]
  input_files_base_dir = rebase_path(".", "//")
}

grit("resources") {
  source = "$target_gen_dir/i_thinking_resources.grd"
  deps = [ ":build_grd" ]
  outputs = [
    "grit/i_thinking_resources.h",
    "grit/i_thinking_resources_map.cc",
    "grit/i_thinking_resources_map.h",
    "i_thinking_resources.pak",
  ]
  output_dir = "$root_gen_dir/chrome"
}
`
  writeUtf8NoBom(filePath, content)
}

function syncWebuiTree(dest: string, inputFiles: string[], webuiDist: string): void {
  ensureDir(dest)
  for (const name of CLEAN_WEBUI_NAMES) {
    const target = path.join(dest, name)
    if (existsSync(target)) {
      rmSync(target, { recursive: true, force: true })
    }
  }

  logger.info(`[browser] Copying WebUI assets ${webuiDist}\\* -> ${dest}`)
  for (const entry of readdirSync(webuiDist, { withFileTypes: true })) {
    if (isSkippedName(entry.name)) {
      logger.warn(`[browser] skip sync entry (not WebUI): ${entry.name}`)
      continue
    }
    const from = path.join(webuiDist, entry.name)
    const to = path.join(dest, entry.name)
    if (entry.isDirectory()) {
      copyDirRecursive(from, to)
    } else {
      copyFileSync(from, to)
    }
  }

  const buildGn = path.join(dest, 'BUILD.gn')
  writeResourcesBuildGn(buildGn, inputFiles)
  logger.info(`[browser] Wrote ${buildGn} (${inputFiles.length} input files)`)
}

function copyDirRecursive(from: string, to: string): void {
  mkdirSync(to, { recursive: true })
  for (const entry of readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name)
    const dst = path.join(to, entry.name)
    if (entry.isDirectory()) {
      copyDirRecursive(src, dst)
    } else {
      copyFileSync(src, dst)
    }
  }
}

function runSync(ctx: BrowserContext): void {
  assertPath(ctx.webuiDist, 'WebUI dist')
  const inputFiles = findDistRelativeFiles(ctx.webuiDist)
  logger.info(`[browser] dist files (${inputFiles.length}):`)
  for (const f of inputFiles) {
    logger.dim(`  ${f}`)
  }
  if (!inputFiles.includes('index.html')) {
    throw new Error('[browser] dist/index.html missing — required for IDR_I_THINKING_INDEX_HTML')
  }

  const relResource = path.join('chrome', 'browser', 'resources', 'i_thinking')
  const overlayDest = path.join(ctx.overlayRoot, relResource)
  syncWebuiTree(overlayDest, inputFiles, ctx.webuiDist)

  if (existsSync(ctx.chromiumRoot)) {
    const chromiumDest = path.join(ctx.chromiumRoot, relResource)
    syncWebuiTree(chromiumDest, inputFiles, ctx.webuiDist)
  } else {
    logger.warn(`[browser] CHROMIUM_ROOT not found (${ctx.chromiumRoot}); skipped live tree`)
  }

  logger.success('[browser] sync done.')
}

export { SyncAction }
