[package]
name              = "identity"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono    = { workspace = true } # 租户/成员的时间戳
entity    = { workspace = true } # 账号 / 租户 / 成员关系实体
sea-orm   = { workspace = true } # 身份持久化查询
serde     = { workspace = true }
thiserror = { workspace = true }
uuid      = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
