/** 常见导航站点，用于 Mirror 灌入大量 navigation 磁贴 */
const NAVIGATION_SITES: readonly { label: string; url: string }[] = [
  { label: '百度', url: 'https://www.baidu.com' },
  { label: '谷歌', url: 'https://www.google.com' },
  { label: '必应', url: 'https://cn.bing.com' },
  { label: '搜狗', url: 'https://www.sogou.com' },
  { label: '淘宝', url: 'https://www.taobao.com' },
  { label: '天猫', url: 'https://www.tmall.com' },
  { label: '京东', url: 'https://www.jd.com' },
  { label: '拼多多', url: 'https://www.pinduoduo.com' },
  { label: '唯品会', url: 'https://www.vip.com' },
  { label: '苏宁', url: 'https://www.suning.com' },
  { label: '亚马逊', url: 'https://www.amazon.cn' },
  { label: '微博', url: 'https://www.weibo.com' },
  { label: '知乎', url: 'https://www.zhihu.com' },
  { label: '豆瓣', url: 'https://www.douban.com' },
  { label: '小红书', url: 'https://www.xiaohongshu.com' },
  { label: '抖音', url: 'https://www.douyin.com' },
  { label: '快手', url: 'https://www.kuaishou.com' },
  { label: '哔哩哔哩', url: 'https://www.bilibili.com' },
  { label: '爱奇艺', url: 'https://www.iqiyi.com' },
  { label: '优酷', url: 'https://www.youku.com' },
  { label: '腾讯视频', url: 'https://v.qq.com' },
  { label: '芒果TV', url: 'https://www.mgtv.com' },
  { label: '网易云音乐', url: 'https://music.163.com' },
  { label: 'QQ音乐', url: 'https://y.qq.com' },
  { label: '喜马拉雅', url: 'https://www.ximalaya.com' },
  { label: '今日头条', url: 'https://www.toutiao.com' },
  { label: '澎湃新闻', url: 'https://www.thepaper.cn' },
  { label: '新浪', url: 'https://www.sina.com.cn' },
  { label: '网易', url: 'https://www.163.com' },
  { label: '搜狐', url: 'https://www.sohu.com' },
  { label: '凤凰网', url: 'https://www.ifeng.com' },
  { label: '央视网', url: 'https://www.cctv.com' },
  { label: '人民网', url: 'https://www.people.com.cn' },
  { label: '新华网', url: 'https://www.xinhuanet.com' },
  { label: 'QQ', url: 'https://www.qq.com' },
  { label: '微信', url: 'https://weixin.qq.com' },
  { label: '美团', url: 'https://www.meituan.com' },
  { label: '大众点评', url: 'https://www.dianping.com' },
  { label: '饿了么', url: 'https://www.ele.me' },
  { label: '携程', url: 'https://www.ctrip.com' },
  { label: '去哪儿', url: 'https://www.qunar.com' },
  { label: '飞猪', url: 'https://www.fliggy.com' },
  { label: '12306', url: 'https://www.12306.cn' },
  { label: '高德地图', url: 'https://www.amap.com' },
  { label: '百度地图', url: 'https://map.baidu.com' },
  { label: '滴滴', url: 'https://www.didiglobal.com' },
  { label: 'GitHub', url: 'https://github.com' },
  { label: 'Gitee', url: 'https://gitee.com' },
  { label: 'GitLab', url: 'https://gitlab.com' },
  { label: 'Stack Overflow', url: 'https://stackoverflow.com' },
  { label: 'MDN', url: 'https://developer.mozilla.org' },
  { label: 'npm', url: 'https://www.npmjs.com' },
  { label: 'Rust', url: 'https://www.rust-lang.org' },
  { label: 'Vue', url: 'https://vuejs.org' },
  { label: 'React', url: 'https://react.dev' },
  { label: 'TypeScript', url: 'https://www.typescriptlang.org' },
  { label: 'Vite', url: 'https://vitejs.dev' },
  { label: 'Tailwind', url: 'https://tailwindcss.com' },
  { label: 'Ant Design', url: 'https://ant.design' },
  { label: 'Element Plus', url: 'https://element-plus.org' },
  { label: 'Iconify', url: 'https://icon-sets.iconify.design' },
  { label: 'Can I Use', url: 'https://caniuse.com' },
  { label: '正则101', url: 'https://regex101.com' },
  { label: 'JSON', url: 'https://json.cn' },
  { label: 'Excalidraw', url: 'https://excalidraw.com' },
  { label: 'Figma', url: 'https://www.figma.com' },
  { label: 'Notion', url: 'https://www.notion.so' },
  { label: '语雀', url: 'https://www.yuque.com' },
  { label: '飞书', url: 'https://www.feishu.cn' },
  { label: '钉钉', url: 'https://www.dingtalk.com' },
  { label: '腾讯文档', url: 'https://docs.qq.com' },
  { label: '石墨文档', url: 'https://shimo.im' },
  { label: 'CSDN', url: 'https://www.csdn.net' },
  { label: '掘金', url: 'https://juejin.cn' },
  { label: '思否', url: 'https://segmentfault.com' },
  { label: '开源中国', url: 'https://www.oschina.net' },
  { label: 'V2EX', url: 'https://www.v2ex.com' },
  { label: '少数派', url: 'https://sspai.com' },
  { label: '即刻', url: 'https://web.okjike.com' },
  { label: 'YouTube', url: 'https://www.youtube.com' },
  { label: 'Twitter', url: 'https://x.com' },
  { label: 'Reddit', url: 'https://www.reddit.com' },
  { label: 'Wikipedia', url: 'https://www.wikipedia.org' },
  { label: 'ChatGPT', url: 'https://chatgpt.com' },
  { label: 'Claude', url: 'https://claude.ai' },
  { label: 'Gemini', url: 'https://gemini.google.com' },
  { label: 'DeepSeek', url: 'https://chat.deepseek.com' },
  { label: '通义千问', url: 'https://tongyi.aliyun.com' },
  { label: 'Kimi', url: 'https://kimi.moonshot.cn' },
  { label: '文心一言', url: 'https://yiyan.baidu.com' },
  { label: '智谱清言', url: 'https://chatglm.cn' },
  { label: 'LeetCode', url: 'https://leetcode.cn' },
  { label: '牛客', url: 'https://www.nowcoder.com' },
  { label: 'Coursera', url: 'https://www.coursera.org' },
  { label: 'B站课堂', url: 'https://www.bilibili.com/cheese' },
  { label: '中国大学MOOC', url: 'https://www.icourse163.org' },
  { label: '支付宝', url: 'https://www.alipay.com' },
  { label: '招商银行', url: 'https://www.cmbchina.com' },
  { label: '东方财富', url: 'https://www.eastmoney.com' },
  { label: '雪球', url: 'https://xueqiu.com' },
  { label: '闲鱼', url: 'https://www.goofish.com' },
  { label: '什么值得买', url: 'https://www.smzdm.com' },
  { label: '汽车之家', url: 'https://www.autohome.com.cn' },
  { label: '安居客', url: 'https://www.anjuke.com' },
  { label: '链家', url: 'https://www.lianjia.com' },
  { label: 'Boss直聘', url: 'https://www.zhipin.com' },
  { label: '智联招聘', url: 'https://www.zhaopin.com' },
  { label: '拉勾', url: 'https://www.lagou.com' },
  { label: '译学馆', url: 'https://www.yxgapp.com' },
  { label: 'IconFont', url: 'https://www.iconfont.cn' },
  { label: 'Unsplash', url: 'https://unsplash.com' },
  { label: 'Pexels', url: 'https://www.pexels.com' },
  { label: 'Dribbble', url: 'https://dribbble.com' },
  { label: 'Product Hunt', url: 'https://www.producthunt.com' },
  { label: 'Hacker News', url: 'https://news.ycombinator.com' },
  { label: 'Arch Wiki', url: 'https://wiki.archlinux.org' },
  { label: 'Docker Hub', url: 'https://hub.docker.com' },
  { label: 'Cloudflare', url: 'https://www.cloudflare.com' },
  { label: 'Vercel', url: 'https://vercel.com' },
  { label: 'Netlify', url: 'https://www.netlify.com' }
]

export { NAVIGATION_SITES }
